stages:
  - deploy

deploy:
  stage: deploy
  script:
    - docker build -t $CI_PROJECT_NAME:$CI_PIPELINE_ID .
    - docker rm -f $CI_PROJECT_NAME || true
    - docker run -e MYSQL_HOST=$MYSQL_HOST -e MYSQL_PORT=$MYSQL_PORT -e MYSQL_USERNAME=$MYSQL_USERNAME -e MYSQL_PASSWORD=$MYSQL_PASSWORD -e MYSQL_DBNAME=$MYSQL_DBNAME -e REDIS_PORT=$REDIS_PORT -e REDIS_PASSWORD=$REDIS_PASSWORD -d --network nginx -p 9000:9000 --name $CI_PROJECT_NAME $CI_PROJECT_NAME:$CI_PIPELINE_ID
  only:
    - master
  tags:
    - master
